<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"> <?=_wishlist('Favoritos')?></h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                        <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin cont_wishlist">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){
var isGridMobile = ($(window).width() <= 767 ? true : false);

$("#jqGrid").GridAdmin({
    search : false,
    entity : 'whishlist',
    redirectOnSelectRow:false,
    gridPager : "#jqGridPager",
    btnSearch: "#btsSearchGridAdmin",
    redirectPath : '',
    pathData : window.location.pathname,
    error : "<?=_('No hay registros')?>",
    deleteFunction : "wishlist_EliminarWhislist",
    colModel: [
        { label: '<?=_('ID')?>', name: 'id', key:true,  width: 50, hidden:true},
        { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
        { label: '<?=_('Fecha')?>', name: 'createdAt',  width: 150,
            
            searchoptions: {
                dataInit: function (element) {
                    $(element).datepicker({
                        id: 'orderDate_datePicker',
                        dateFormat:"yy-mm-dd",
                        maxDate: "+0D",
                        showOn: 'focus'
                    });
                },
                sopt: ["ge","le","eq"]
            }
        },
        { label: '<?=_('Imagen')?>', name: 'item_image', width: 100, search:false },
        { label: '<?=_('Item')?>', name: 'item', width: 250 },
        { 
        name: 'acciones', 
        index: 'acciones', 
        width: 180, 
        align: 'center', 
        sortable: false, 
        search: false,
        formatter: creadorDeBotones,
        }
    ],
    subGrid: false,
    subGridRowExpanded: function(){},
    width:700
});
});

function creadorDeBotones(cellvalue, options, rowObject) {

    var id = options.rowId;
    
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton;
}

</script>
